# Generated by Django 3.1 on 2020-09-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='oldLegendSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverName', models.CharField(max_length=18)),
                ('ip', models.CharField(max_length=18)),
                ('time', models.DateTimeField()),
                ('type', models.CharField(max_length=18)),
                ('introduce', models.CharField(max_length=40)),
                ('QQ', models.CharField(max_length=18)),
                ('isActive', models.BooleanField(default=False)),
                ('href', models.CharField(default='null', max_length=100)),
                ('onPage', models.CharField(default='normal', max_length=10)),
            ],
        ),
    ]
